name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-build:
    name: Backend build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    strategy:
      matrix:
        node-version: [16.x]
        architecture: [x64]
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

      - name: USE NODEJS ${{ matrix.node-version }} - ${{ matrix.architecture }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: INSTALL PROJECT DEPENDENCIES (NPM)
        run: npm ci

      - name: BUILD APPLICATION
        run: npm run build --if-present

  backend-unit-test:
    name: Backend Unit test
    needs: backend-build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    strategy:
      matrix:
        node-version: [16.x]
        architecture: [x64]
    steps:
      - name: CHECK-OUT GIT REPOSITORY
        uses: actions/checkout@v2

      - name: USE NODEJS ${{ matrix.node-version }} - ${{ matrix.architecture }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: INSTALL PROJECT DEPENDENCIES (NPM)
        run: npm ci

      - name: BUILD APPLICATION
        run: npm run build --if-present

      - name: START DOCKER TEST DATABASE
        run: npm run docker:up

      - name: UNIT TEST (JEST)
        run: npm run test:ci

      - name: STOP DOCKER TEST DATABASE
        run: npm run docker:down